### ISSUE TITLE
n98-magerun doesn't clear the DI Container cache on cache:clean

### ISSUE THREAD

**Issue by andytson** [inviqa/magento-symfony-container#5]
```
php -f ../bin/n98-magerun.phar cache:clean
block_html cache cleaned
collections cache cleaned
config cache cleaned
config_api cache cleaned
config_api2 cache cleaned
eav cache cleaned
full_page cache cleaned
layout cache cleaned
translate cache cleaned
```

**Comment by jon-acker** [comment]
I believe this is an issue with magerun, I've opened a PR for it to add custom caches to the list of caches cleaned, which fixes this: https://github.com/netz98/n98-magerun/pull/704

**Comment by tkn98** [comment]
@andytson: What is the DI Container cache? Can you share some details? And are you able to test this against the unstable version? I'll merge the PR and some confirmation from your end would be great.

Edit: Just seeing, this is a different (than magerun) project, this clarify things up.

@jon-acker: Thanks for looking into this.

**Comment by jon-acker** [comment]
@tkn98 you can probably ignore the comment about the DI container cache - its an example of a custom cache we're using. I've tested the built magerun.phar against our application that uses custom cache types and it works fine:
we get the following output:
<img width="467" alt="screen shot 2015-10-08 at 10 42 23" src="https://cloud.githubusercontent.com/assets/956800/10362909/2d57df5c-6da9-11e5-89bb-8c4a284681c4.png">

If you _are_ interested in details of what this caches, you can have a look at the project: 
https://github.com/inviqa/magento-symfony-container
It creates its own cache type in order to be able to clear/refresh a cached dependency-injection container.

Without my change it will only clear the magento core cache types (i.e. ignoring inviqa_symfonyContainer)

**Comment by jon-acker** [comment]
Version 1.97.6 of magerun has been released, which contains the above fix.
